### ISSUE TITLE
[Help Wanted] [PLT-6440] Add Go code samples to API reference for user endpoints

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-api-reference#229]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "APIv4" community channel](https://pre-release.mattermost.com/core/channels/apiv4).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6440)

OpenAPI (formerly known as Swagger 2.0) supports adding code samples for different languages by using the `x-code-sample` attribute on requests.

We need help adding code samples to each of the user endpoints in API version 4.

I added a couple examples of what it should look like here:
https://github.com/mattermost/mattermost-api-reference/pull/228/files#diff-05cb92fde37b9148b077595fca2427fbR47

The Go driver itself lives here: https://github.com/mattermost/platform/blob/master/model/client4.go

If you need examples of the driver in use, you can look at our unit tests using it here: 
https://github.com/mattermost/platform/tree/master/api4/user_test.go

If you have any questions ask @joram in the APIv4 channel on pre-release.mattermost.com or mention me on GitHub @jwilander

**Comment by cpanato** [comment]
i can work

**Comment by cpanato** [comment]
will start with the `brand` endpoints

**Comment by cpanato** [comment]
for `brand` PR: https://github.com/mattermost/mattermost-api-reference/pull/236

**Comment by cpanato** [comment]
for `channels` PR: https://github.com/mattermost/mattermost-api-reference/pull/240

**Comment by cpanato** [comment]
for `commands` PR: https://github.com/mattermost/mattermost-api-reference/pull/245

**Comment by cpanato** [comment]
for `system` PR: https://github.com/mattermost/mattermost-api-reference/pull/250

**Comment by jasonblais** [comment]
Re-created help wanted ticket at https://github.com/mattermost/mattermost-server/issues/10606, closing
