### ISSUE TITLE
'Add a user' missing required flag in request body

### ISSUE THREAD

**Issue by Vaelor** [mattermost/mattermost-api-reference#260]
https://api.mattermost.com/v4/#tag/channels%2Fpaths%2F~1channels~1%7Bchannel_id%7D~1members%2Fpost

'Add a user' says the path parameter `channel_id` is required.
Making a request with only this information results in a HTTP 400 Error.
Adding the 'user_id' in the request body works. (Makes sense ;-) )

The documentation does not mark it as required, probably because in the yaml file it says:
```yaml
          schema:
            $ref: '#/definitions/ChannelMember'
```
https://github.com/mattermost/mattermost-api-reference/blob/master/v4/source/channels.yaml#L789

Adding
```yaml
required:
  - user_id
```
Does not work, because additional values alongside $ref are ignored.

I guess using a $ref to the schema is not working in this case?

**Comment by saturninoabril** [comment]
@Vaelor `user_id` is a property of `ChannelMember` as defined [here](https://github.com/mattermost/mattermost-api-reference/blob/master/v4/source/definitions.yaml#L128) which is set as required in API documentation.
```
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/ChannelMember'
```
On API call, the `user_id` in the request body is being mapped to a `ChannelMember`. We are using `ChannelMember` as required for consistency and validation in requesting to this API.

**Comment by saturninoabril** [comment]
I'm closing the ticket now.

**Comment by Vaelor** [comment]
Yeah, but in the documentation the required fields are not appearing as required.
Other requests mark which fields in the request body are required, like here:
[Create a channel](https://api.mattermost.com/v4/#tag/channels)
Comparing this with this one
[Add a user](https://api.mattermost.com/v4/#tag/channels%2Fpaths%2F~1channels~1{channel_id}~1members%2Fget)

in the first one, required fields are marked as such, while in the second there are required fields but not marked.

It is no big thing so I am okay with this being closed. ;-)
