### ISSUE TITLE
/users/status/ids endpoint documentation

### ISSUE THREAD

**Issue by xlatb** [mattermost/mattermost-api-reference#313]
In /v4/source/status.yaml, the /users/status/ids endpoint is listed as a GET method with no parameters.

In reality it seems to want a POST where the request body is an array of user ids, as can be seen at the following URLs:

https://github.com/mattermost/mattermost-server/blob/4491b5ecdfad96959f9a9ab32a5f127bbfa7eac5/api4/status.go#L19
https://github.com/mattermost/mattermost-server/blob/4491b5ecdfad96959f9a9ab32a5f127bbfa7eac5/api4/status.go#L44

**Comment by hmhealey** [comment]
Hi @xlatb,

Thanks for the report. I've created a Jira ticket ([link](https://mattermost.atlassian.net/browse/PLT-8441) to make sure that gets added. If you'd also like to help out by adding it, that'd be great

**Comment by esethna** [comment]
Closing to track with this ticket: https://github.com/mattermost/mattermost-api-reference/issues/314

Let us know if you'd like to work on it

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.
