### ISSUE TITLE
number format in yaml specifies integer type for create_at, update_at, delete_at but returns int64

### ISSUE THREAD

**Issue by greigs** [mattermost/mattermost-api-reference#345]
If the data coming back from the API is an int64, as it appears to be, the optional format flag should be used to specify it as int64, not just integer (which assumes int32). See 
[https://swagger.io/docs/specification/data-models/data-types/](https://swagger.io/docs/specification/data-models/data-types/) 

Other integers that use this same timestamp style should also specify the int64 format.

**Comment by streamba** [comment]
I've modified the v4 spec to change all integers to integers with the format int64 and it solved my immediate issue. May be useful until this is closed.
https://storage.googleapis.com/openapi-spec/mattermost-openapi-v4.yaml

**Comment by amyblais** [comment]
Hi @greigs, I've created a ticket for our engineers to take a look: https://mattermost.atlassian.net/browse/MM-10270.

**Comment by lindy65** [comment]
Thanks, I'll close this issue off for now and we can track via the above-linked ticket.
