### ISSUE TITLE
Add inclide_deleted flag to API documentation of 'get channel by name' method

### ISSUE THREAD

**Issue by DenKoren** [mattermost/mattermost-api-reference#408]
As far as I see from source codes of Mattermost and from https://mattermost.atlassian.net/browse/MM-11350 there is a special method parameter which makes method to search across deleted channels as well.

Please, list this parameter in API documentation and note that it requires manage_team privilege.

Thanks.

**Comment by jwilander** [comment]
That documentation was added with https://github.com/mattermost/mattermost-api-reference/pull/399 and https://github.com/mattermost/mattermost-api-reference/pull/398. Is there some specific part of the API reference that it's missing from?

**Comment by DenKoren** [comment]
Sorry.

I’m sure it was not listed on https://api.mattermost.com/#tag/channels%2Fpaths%2F~1teams~1%7Bteam_id%7D~1channels~1name~1%7Bchannel_name%7D%2Fget page few hours ago.


Now I see it, but there is no info about ‘manage_team’ privilege. Am I correct that it is required for the caller to see the deleted channel?

**Comment by jwilander** [comment]
I do not think so, looking at the code I don't see any permission check for 'manage_team' on deleted channels

**Comment by hanzei** [comment]
Hey @DenKoren,

Did the comment above helped you debug your problem? Do you have further questions?
