### ISSUE TITLE
POST /api/v4/ldap/sync returns 200 when running Team Edition

### ISSUE THREAD

**Issue by maruTA-bis5** [mattermost/mattermost-api-reference#424]
#### Summary
In reference https://api.mattermost.com/#tag/LDAP%2Fpaths%2F~1ldap~1sync%2Fpost , `POST /api/v4/ldap/sync` returns `200` or `501`.
But Mattermost Team Edition 5.8.0 server returns `200`.

LDAP feature is available in Enterprise Edition, so TE should returns `501` or remove `501` response in reference.

#### Steps to reproduce
1. Login as system administrator.
2. Send `POST /api/v4/ldap/sync` request.

#### Expected behavior
Server may returns `501 Feature is disabled` response.

#### Observed behavior (that appears unintentional) 
Server returns `200 OK` response and response body is `{"status":"OK"}`

Here is my test result using curl.
```
$ curl -i -d '{"login_id":"testuser","password":"password"}' http://192.168.99.100:8065/api/v4/users/login
HTTP/1.1 200 OK
Content-Type: application/json
Set-Cookie: MMAUTHTOKEN=w5n8dfnq83rbzfehkp41xxffdr; Path=/; Expires=Tue, 26 Mar 2019 13:41:39 GMT; Max-Age=2592000; HttpOnly
Set-Cookie: MMUSERID=ku9w5umiojf13ptwgjzog6bope; Path=/; Expires=Tue, 26 Mar 2019 13:41:39 GMT; Max-Age=2592000
Token: w5n8dfnq83rbzfehkp41xxffdr
X-Request-Id: 1jnj844befbzudzn8g7ns9c4se
X-Version-Id: 5.8.0.5.8.0.d374af64e316cdd1e7938e8fa4a8ffd2.false
Date: Sun, 24 Feb 2019 13:41:39 GMT
Content-Length: 650

{"id":"ku9w5umiojf13ptwgjzog6bope","create_at":1551015294566,"update_at":1551015297407,"delete_at":0,"username":"testuser","auth_data":"","auth_service":"","email":"testuser@inbucket.local","nickname":"","first_name":"","last_name":"","position":"","roles":"system_admin system_user","allow_marketing":true,"notify_props":{"channel":"true","comments":"never","desktop":"mention","desktop_sound":"true","email":"true","first_name":"false","mention_keys":"testuser,@testuser","push":"mention","push_status":"away"},"last_password_update":1551015294566,"locale":"en","timezone":{"automaticTimezone":"","manualTimezone":"","useAutomaticTimezone":"true"}}

$ curl -i -X POST -H "Authorization: Bearer w5n8dfnq83rbzfehkp41xxffdr" http://192.168.99.100:8065/api/v4/ldap/sync
HTTP/1.1 200 OK
Content-Type: application/json
X-Request-Id: z445hj9bnbrf5d9wc8f333467w
X-Version-Id: 5.8.0.5.8.0.d374af64e316cdd1e7938e8fa4a8ffd2.false
Date: Sun, 24 Feb 2019 13:42:13 GMT
Content-Length: 15

{"status":"OK"}
```

#### Possible fixes
[App.SyncLdap](https://github.com/mattermost/mattermost-server/blob/v5.8.0/app/ldap.go#L16) can not return anything because that run all statements in goroutine (I think it is by design),

**Comment by amyblais** [comment]
@mkraft Does this look like a possible API response bug for LDAP sync in TE?

**Comment by mkraft** [comment]
@amyblais No considering that endpoint hasn't changed since 2017 it isn't related to LDAP sync and likely the bug has always been there. 

I'll create a ticket for the the platform team to fix it.

**Comment by mkraft** [comment]
Tracking here going forward: https://mattermost.atlassian.net/browse/MM-14590
