### ISSUE TITLE
'D' channel type is not documented

### ISSUE THREAD

**Issue by Psycojoker** [mattermost/mattermost-api-reference#429]
Hello,

Only 'O' and 'P' channel types are defined in the documentation here https://api.mattermost.com/#tag/channels

'D', which I though was for 'Deleted' (because their name was super weird), turned out to be 'Direct' and their name to be "{my-id}__{other-user-id}" which doesn't seems to be explained somewhere (I couldn't find this information)

Kind regards,

**Comment by coltoneshaw** [comment]
@cpanato - I think this can be closed. The API doesn't return direct messages when hitting the channels endpoint, only O/P. 

Maybe this can be added to product docs?
