### ISSUE TITLE
[Help Wanted] Document '/hooks/outgoing/list' API for Mattermost 3.5

### ISSUE THREAD

**Issue by hmhealey** [mattermost/mattermost-api-reference#43]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Details:**
The API endpoint `api/v3/teams/{team_id:[A-Za-z0-9]+}/hooks/outgoing/list` is undocumented and we would love help getting it documented. There's some rough documentation for it available [on our forums](https://forum.mattermost.org/t/is-there-support-for-creating-webhooks-using-mattermost-api/2400/3).

Please look at the [release-3.5 branch of mattermost/platform](https://github.com/mattermost/platform/tree/release-3.5/api) when documenting this API. Looking at our [Go driver](https://github.com/mattermost/platform/blob/release-3.5/model/client.go) and [JavaScript driver](https://github.com/mattermost/platform/blob/release-3.5/webapp/client/client.jsx) might help as well.

Also please see [CONTRIBUTING.md](https://github.com/mattermost/mattermost-api-reference/blob/master/CONTRIBUTING.md) for help with contributing to this repo. If you have any questions, feel free to ask!

**Comment by ruzette** [comment]
Hi,

May I contribute to working on this issue? And which branch, master or release-3.6, should I checkout and create a branch from? 

I'm seeing that there were changes in the branch release-3.6 that were not in the master and that branch looks more updated. 

Thanks thanks!
Ruzette

**Comment by jwilander** [comment]
Sorry, completely missed your message! `master` is the right place for it and I'll update the old branches with the changes if they should be there. Thanks for working on this!
