### ISSUE TITLE
autorest claims your yaml file is invalid

### ISSUE THREAD

**Issue by nikkilocke** [mattermost/mattermost-api-reference#451]
I am writing a C# wrapper for the Mattermost API. I started doing it by hand, but I discovered [autorest](https://github.com/Azure/autorest), and tried to run it on the mattermost-api-v4.yaml file.

At first attempt, I got the following errors:

		PS E:\mattermost-api-reference> autorest --input-file=mattermost-openapi-v4.yaml --csharp --namespace=MattermostApi --output-folder=CSharp
		AutoRest code generation utility [version: 2.0.4283; node: v10.16.0]
		(C) 2018 Microsoft Corporation.
		https://aka.ms/autorest
		   Loading AutoRest core      'C:\Users\Nikki\.autorest\@microsoft.azure_autorest-core@2.0.4383\node_modules\@microsoft.
		azure\autorest-core\dist' (2.0.4383)
		   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.82)
		   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
		ERROR: Schema violation: Data does not match any schemas from 'oneOf'
			- file:///E:/mattermost-api-reference/mattermost-openapi-v4.yaml:8885:8 ($.paths["/brand/image"].delete.responses["404"])
		ERROR: Schema violation: Data does not match any schemas from 'oneOf'
			- file:///E:/mattermost-api-reference/mattermost-openapi-v4.yaml:8800:8 ($.paths["/brand/image"].get.responses["404"])
		ERROR: Schema violation: Data does not match any schemas from 'oneOf'
			- file:///E:/mattermost-api-reference/mattermost-openapi-v4.yaml:7083:8 ($.paths["/system/ping"].get.responses["500"])
		FATAL: swagger-document/individual/schema-validator - FAILED
		FATAL: Error: [OperationAbortedException] Error occurred. Exiting.
		Process() cancelled due to exception : [OperationAbortedException] Error occurred. Exiting.

I deleted the offending responses, and then got the following error:

		PS E:\mattermost-api-reference> autorest --input-file=mattermost-openapi-v4.yaml --csharp --namespace=MattermostApi --output-folder=CSharp
		AutoRest code generation utility [version: 2.0.4283; node: v10.16.0]
		(C) 2018 Microsoft Corporation.
		https://aka.ms/autorest
		   Loading AutoRest core      'C:\Users\Nikki\.autorest\@microsoft.azure_autorest-core@2.0.4383\node_modules\@microsoft.
		azure\autorest-core\dist' (2.0.4383)
		   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.82)
		   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
		FATAL: System.Exception: Invalid Swagger: Missing 'items' definition of an 'array' type.
		   at AutoRest.Modeler.ObjectBuilder.BuildServiceType(String serviceTypeName, Boolean required) in /opt/vsts/work/1/s/src/ObjectBuilder.cs:line 173
		   at AutoRest.Modeler.SchemaBuilder.ParentBuildServiceType(String serviceTypeName, Boolean required) in /opt/vsts/work/1/s/src/SchemaBuilder.cs:line 217
		   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in /opt/vsts/work/1/s/src/SchemaBuilder.cs:line 48   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in /opt/vsts/work/1/s/sr
		c/SchemaBuilder.cs:line 133
		   at AutoRest.Modeler.ParameterBuilder.BuildServiceType(String serviceTypeName, Boolean required) in /opt/vsts/work/1/s/src/ParameterBuilder.cs:line 92
		   at AutoRest.Modeler.ParameterBuilder.Build() in /opt/vsts/work/1/s/src/ParameterBuilder.cs:line 54
		   at AutoRest.Modeler.OperationBuilder.BuildMethodParameters(Method method) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 291
		   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 100
		   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 404
		   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 106
		   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
		--- End of stack trace from previous location where exception was thrown ---
		   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		   at NewPlugin.<Process>d__15.MoveNext()
		FATAL: csharp/imodeler1 - FAILED
		FATAL: Error: Plugin imodeler1 reported failure.
		Process() cancelled due to exception : Plugin imodeler1 reported failure.
		  Error: Plugin imodeler1 reported failure.

Note - I also got the error `Error: OperationId is required for all operations`, but I solved that with a configuration file:

		# OpenData Transport
		> see https://aka.ms/autorest

		This is the AutoRest configuration file for the Transport APIs.

		---

		#### Basic Information 
		These are the global settings for Transport APIs.

		``` yaml
		# list all the input OpenAPI files (may be YAML, JSON, or Literate- OpenAPI markdown)
		input-file:
		  - mattermost-openapi-v4.yaml

		# this allows you to programatically tweak the swagger file before it is modeled.
		directive:
		  from: swagger-document # do it globally 
		  where: $.paths.*.* 

		  # set each operationId to 'Transport_<Tag>'
		  transform: $.operationId = `Transport_${$.tags[0]}`

**Comment by schemacs** [comment]
After run `make build`, with this conf.yml:

```yaml
---
input-file:
  - v4/html/static/mattermost-openapi-v4.yaml
directive:
  from: swagger-document # do it globally
  where: $.paths.*.*
  transform: $.operationId = `MyAPI_${$.tags[0]}
```

run `autorest --python --output-folder=/tmp/pymm --verbose --debug --version=2.0.4390 conf.yml`:

```
...
DEBUG: Emitting 'source-file-python' at file:///tmp/pymm/mattermostopenapiv4/operations/init.py
DEBUG: Emitting 'source-file-python' at file:///tmp/pymm/mattermostopenapiv4/operations/my_api_operations.py
DEBUG: python/emitter - END
  Error: ENAMETOOLONG: name too long, open '/tmp/pymm2/mattermostopenapiv4/models/body_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_model_py3.py'
```

@nikkilocke Will `Transport_${$.tags[0]}` get duplicate operationId value?

**Comment by schemacs** [comment]
I have tested two operations with the same tag, autorest will append an index number to functions like `brand` and `brand1`. But how could autorest come up with such a long filename/path? Maybe I should post this issue to azure/autorest.

**Comment by hanzei** [comment]
Hi @nikkilocke,

Thanks for reporting this issue. A couple of bugs in the definitions where fixed with https://github.com/mattermost/mattermost-api-reference/pull/488. Could you please check again, if you encounter any issues?

**Comment by reflog** [comment]
@schemacs we've ported our definition to OpenAPI 3 spec. Can you try using it and see if you have any issues?
