### ISSUE TITLE
'Get channel members for user' actually returns 'membership' info

### ISSUE THREAD

**Issue by bradjcoughlin** [mattermost/mattermost-api-reference#483]
The data objects returned from the 'Get channel members for user' are meta-information about the membership status of the user specified in the API call, not a list of members on the team as documented ('Get all channel members on a team for a user.').

I propose updating the documentation to reflect that the response lists the channels to which the specified user belongs and the related membership roles for that user (channel_user, channel_admin, etc).

Here's an example of the API response:
```
{
  "data": [
    {
      "channel_id": "ipwjyizq9pnimxpup8xw3zz4ir",
      "user_id": "657eyu1stf8z3e1kncrsopfaka",
      "roles": "channel_user channel_admin",
      "last_viewed_at": 1570121696257,
      "msg_count": 0,
      "mention_count": 0,
      "notify_props": {
        "desktop": "default",
        "email": "default",
        "ignore_channel_mentions": "default",
        "mark_unread": "all",
        "push": "default"
      },
      "last_update_at": 1570121696257,
      "scheme_guest": false,
      "scheme_user": true,
      "scheme_admin": true,
      "explicit_roles": ""
    },
    {
      "channel_id": "k1ngdpx6jigsupzwegj1e6yt6e",
      "user_id": "657eyu1stf8z3e1kncrsopfaka",
      "roles": "channel_user channel_admin",
      "last_viewed_at": 1570120045131,
      "msg_count": 1,
      "mention_count": 0,
      "notify_props": {
        "desktop": "default",
        "email": "default",
        "ignore_channel_mentions": "default",
        "mark_unread": "all",
        "push": "default"
      },
      "last_update_at": 1570120045131,
      "scheme_guest": false,
      "scheme_user": true,
      "scheme_admin": true,
      "explicit_roles": ""
    }
  ]
}
```
https://github.com/mattermost/mattermost-api-reference/blob/d0287798f5023809777d4a21033827ac25ec328c/v4/source/channels.yaml#L1399

**Comment by crspeller** [comment]
@bradjcoughlin Not sure what you are looking for here. If the docs are wrong, updating them to be right is a good thing.

**Comment by bradjcoughlin** [comment]
@crspeller I wasn’t sure of the process for updating documentation. Happy to just submit a PR.

**Comment by crspeller** [comment]
@bradjcoughlin Ya go ahead!
