### ISSUE TITLE
OpenAPI spec lacks proper authorization securityDefinitions

### ISSUE THREAD

**Issue by devth** [mattermost/mattermost-api-reference#485]
Since the openapi.yaml spec doesn't specify `securityDefinitions` generated clients will lack the proper code to set the `Authorization` header.

**Comment by devth** [comment]
Any thoughts on this?

**Comment by hanzei** [comment]
@jupenur I lack the domain knowable to properly triage this issue. Can you help?

**Comment by devth** [comment]
Here are the docs if it helps: https://swagger.io/docs/specification/2-0/authentication/

**Comment by jupenur** [comment]
@hanzei I can't say that I know much about the OpenAPI spec, and certainly not enough to write a fix, but this seems like a valid issue for sure. Authorization is only described in text in `introduction.yaml` and not in a format usable for client generation.

**Comment by hanzei** [comment]
Mattermost has a lot of scopes for authentication. Hence, it a lot of work to add them all.

@devth Would you be interested on working on this?

**Comment by devth** [comment]
I don't know anything about Mattermost codebase and I only just started using Mattermost itself. Just trying to use its OpenAPI spec to generate clients to consume the API. I'm happy to help test / provide feedback.

**Comment by reflog** [comment]
@hanzei - I'll take over this issue
