### ISSUE TITLE
Document return values of golang api

### ISSUE THREAD

**Issue by XANi** [mattermost/mattermost-api-reference#52]
Trying to write anything more advanced is exercise in frustration, most commands require digging in source code just to guess what output they return [for example](https://godoc.org/github.com/mattermost/platform/model#Client.GetProfilesInChannel) have no ducumentation saying that it returns `map[string]*User`, and that is pretty much same with every function. 

Also is there a reason why every response is wrapped in `*Result.Data` interface and need to be cast every time to be used ?

**Comment by jwilander** [comment]
Hi @XANi, would you mind posting this in the issues section of the [mattermost/platform](https://github.com/mattermost/platform/issues) repository? Your question seems more directed towards the golang driver while this repository is for the API reference.

**Comment by XANi** [comment]
@jwilander sure mattermost/platform#4723
