### ISSUE TITLE
User props is not fully described in API reference

### ISSUE THREAD

**Issue by vblz** [mattermost/mattermost-api-reference#643]
Everywhere in the API reference User Props is described as `object`. For instance https://api.mattermost.com/#operation/CreateUser .
Regarding to https://www.json.org/json-en.html JSON object can have members of any JSON types.

But in official drivers the field `props` has type `map[string]string`
https://github.com/mattermost/mattermost-server/blob/d1eeafb29ff822cf6d9850a5307ab37c61fbc445/model/user.go#L85
https://github.com/mattermost/mattermost-redux/blob/3d1028034d7677adfda58e91b9a5dcaf1bc0ff99/src/types/users.ts#L42

Proposal:
In the API reference clearly specify that User Props can have members only of string type

**Comment by cwarnermm** [comment]
@mkraft - Would a member of your team be able to assist with this issue?

**Comment by mkraft** [comment]
@vblz The word "object" is actually correct in this case in that the required type *is* an object, an object that happens to have other constraints. Also the constraints are detailed within the API documentation.

<img width="1339" alt="Screen Shot 2022-03-08 at 4 56 11 PM" src="https://user-images.githubusercontent.com/1149597/157332665-b92726f3-e77b-4a2d-90f8-c387e3e2e35b.png">
.

**Comment by vblz** [comment]
@mkraft I didn't mean whole object to pass, but only `props` field. 
<img width="950" alt="image" src="https://user-images.githubusercontent.com/2076171/157393837-971eade5-eb74-40b5-99d6-db9f8a885551.png">
According to the code I linked above  you can not pass such a valid JSON object there
```
...
 "props": {"a": 1, "b":["list", "example"]}
 ...
```
 but there is no mention about this limitation in api documentation and only way to find it out is checking source code.

**Comment by mkraft** [comment]
@vblz Ah yes good point, `props` isn't well documented like `notify_props` is. Is this something you would be interested in submitting a pull request for? If not, no worries we can add it as a help wanted. Either way, thanks for identifying it.

**Comment by vblz** [comment]
@mkraft it's better to add "help wanted" tag

**Comment by ikjnv** [comment]
I would like to work on this
