### ISSUE TITLE
Dead endpoint - /api/v4/saml/metadatafromidp

### ISSUE THREAD

**Issue by coltoneshaw** [mattermost/mattermost-api-reference#655]
### Get IDP Metadata
- test url - https://community.mattermost.com/api/v4/saml/metadatafromidp
- docs - https://api.mattermost.com/#operation/GetSamlMetadataFromIdp
Not even a real API call

```json
{"id":"api.context.404.app_error","message":"Sorry, we could not find the page.","detailed_error":"There doesn't appear to be an api call for the url='/api/v4/saml/metadatafromidp'.  Typo? are you missing a team_id or user_id as part of the url?","status_code":404}
```

**Comment by gmerz** [comment]
The endpoint seems to be "POST" only. At least a post request to the same URL yields:

```json
{"id":"api.context.permissions.app_error","message":"You do not have the appropriate permissions.","detailed_error":"userId=, permission=get_saml_metadata_from_idp,","request_id":"r9wj5xi6mjf19kbn4dfq8cxdwc","status_code":403}
```

However, the go-client also sets [saml_metadata_url in the request body](https://github.com/mattermost/mattermost-server/blob/dcd4e50bdebaf1f89226f3a7d72e83f3c7e8dc00/model/client4.go#L4954), which is not mentioned in the API documentation.

**Comment by cwarnermm** [comment]
@mkraft - Is this something your team can assist with?

**Comment by mkraft** [comment]
Submitted https://github.com/mattermost/mattermost-api-reference/pull/685.
