### ISSUE TITLE
Misleading API reference on Webhook

### ISSUE THREAD

**Issue by safakkizkin** [mattermost/mattermost-api-reference#690]
on API Documentation about incoming webhook there was no sign of requirement about `hook_id` in payload for update the webhook (IMAGE_1). 
With given information I tried to request with given information on API document, I got error as You can see on image 2.

I do some research and looked up the request when we do update on Mattermost Desktop application there was `id` instead of `hook_id`.
![Attachment_1](https://user-images.githubusercontent.com/22755582/162970691-12ad6109-9d7d-4af5-be11-a8f29c260c6c.png)

![Attachment_2](https://user-images.githubusercontent.com/22755582/162970704-e14f8454-3987-4922-a082-308223c7e65a.jpg)

**Comment by cwarnermm** [comment]
Thanks @safakkizkin! Would you be open to creating a PR with missing payload details?
