### ISSUE TITLE
Search fails on api.mattermost.com

### ISSUE THREAD

**Issue by safakkizkin** [mattermost/mattermost-api-reference#709]
on [api.mattermost.com](https://api.mattermost.com) using searchbox comes with blank screen, explaind as image below. I did some research and I did some research and it occurs because of redoc. 

The issue only on website, there is nothing wrong when built from source code.

<img width="1748" alt="image" src="https://user-images.githubusercontent.com/22755582/181355490-cac15d0a-d34e-4eb3-b75c-79ea91d48e32.png">

**Comment by cwarnermm** [comment]
Thanks, @safakkizkin! We're actively investigating this issue. CC @mickmister
